{
 "title": "Aerospike HDF",
 "description": "Aerospike HDF",
 "tags": [
  "Monitoring",
  "vectors",
  "HDF",
  "ANN"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_HDF", "label": "Datasource", "query": "prometheus" },
   {
    "name": "client",
    "label": "Client",
    "query": {
     "query": "label_values(aerospike_hdf_heartbeat,instance)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_hdf_heartbeat,ns)"
    }
   },
   {
    "name": "set",
    "label": "Set",
    "query": {
     "query": "label_values(aerospike_hdf_heartbeat{ns=~\"$namespace\"},set)"
    }
   },
   {
    "name": "idxns",
    "label": "Idx Namespace",
    "query": {
     "query": "label_values(aerospike_hdf_heartbeat,idxns)"
    }
   },
   {
    "name": "idxname",
    "label": "Index name",
    "query": {
     "query": "label_values(aerospike_hdf_heartbeat{idxns=~\"$idxns\"},idx)"
    }
   },
   {
    "name": "QueryRun",
    "label": "Query Run",
    "query": {
     "query": "label_values(aerospike_hdf_query_total{idx=~\"$idxname\", ns=~\"$idxns\"},run)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dataset",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distance Type",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dataset Size (records)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Diminsions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Status",
   "type": "stat",
   "description": "The Index Status. If 'N/A' can indicate the index dosn't exists.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(aerospike_hdf_exception{instance=~\"$client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HNSW Params",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Mode",
   "type": "stat",
   "description": "The Index's Mode.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aerospike Set",
   "type": "stat",
   "description": "The name of the Aerospike Namespace ans Set where the vector values are stored",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}, \"fullname\", \".\", \"ns\", \"set\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Index",
   "type": "stat",
   "description": "The location of where the vector index is stored within the Aerospike DB. ",
   "gridPos": { "h": 3, "w": 10, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}, \"fullname\", \".\", \"idxns\",\"idx\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "aerospike_hdf_exception{ns=~\"$idxns\", instance=~\"$client\", idx=~\"$idxname\", run=~\"$QueryRun\"}",
       "legendFormat": "{{instance}} - {{ns}}.{{idx}} Run: {{run}} {{exception_type}}"
      },
      {
       "expr": "aerospike_hdf_exception{ns=~\"$namespace\", instance=~\"$client\", set=~\"$set\"}",
       "legendFormat": "{{instance}} - {{ns}}.{{set}} {{exception_type}}"
      }
     ]
    }
   ]
  },
  { "title": "Population", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Population Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Upserted Vectors",
   "type": "gauge",
   "description": "The current total of vectors upserted.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aerospike_hdf_populate_total{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records Queued to be Merged into DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "aerospike_hdf_vector_uncommitted{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "{{instance}} {{idxns}}.{{idx}}"
    }
   ]
  },
  {
   "title": "Index Action",
   "type": "stat",
   "description": "Actions (drop, create, etc.) performed against the Index",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "After Population Index Action",
   "type": "stat",
   "description": "After the records are populated, what  index action is performed...",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "stat",
   "description": "What population concurrency action is being applied.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wait for Index Completion Timeout",
   "type": "stat",
   "description": "The number of seconds to wait before continue when Index Completion is Running",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exhausted Resource Handling",
   "type": "stat",
   "description": "If a resource exhausted error occurs, what action should be performed. ",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Populateion (rate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(aerospike_hdf_populate_total{instance=~\"$client\", ns=~\"$namespace\", set=~\"$set\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{ns}}.{{set}} {{type}}"
    },
    {
     "expr": "aerospike_hdf_waitidxcompletion_total{ns=\"$idxns\", idx=\"$idxname\", instance=~\"$client\"}",
     "legendFormat": "{{type}} {{instance}}-{{ns}}.{{idx}}"
    }
   ]
  },
  { "title": "Vector Search/Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Runs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Queries each Run",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Return How Many Neighbors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", idxns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ef",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{instance=~\"$client\", ns=~\"$idxns\", idx=~\"$idxname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Query Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records per Seconds",
   "type": "stat",
   "description": "Query per Seconds (QPS)",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall Method",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}, \"recalltype\", \"-\", \"querydistance\",\"querymetric\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall (Distance)",
   "type": "stat",
   "description": "This recall is calculated based on the distance between neighbors based on the ANN formulas.",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recall (Aerospike Distance)",
   "type": "stat",
   "description": "This recall is calculated based on the distance as returned by the Aerospike API using the ANN formulas.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KNN Recall (Nbors)",
   "type": "stat",
   "description": "This recall is calculated using the Big ANN's KNN neighbor formulas (distance is not used).",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS Status",
   "type": "stat",
   "description": "Query Restriction Status",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "aerospike_hdf_heartbeat{idx=~\"$idxname\", instance=~\"$client\", idxns=~\"$idxns\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vector Search (rate)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(aerospike_hdf_query_total{ns=~\"$idxns\", idx=~\"$idxname\", instance=~\"$client\", run=~\"$QueryRun\"}[$__rate_interval])",
     "legendFormat": "{{instance}}-{{ns}}.{{idx}} Run {{run}}"
    }
   ]
  },
  {
   "title": "Vector Search Latency Buckets (ms)",
   "type": "heatmap",
   "description": "The number of queries that fall within a certain latency buckets in milliseconds",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "sum by(le) (aerospike_hdf_queryhist_milliseconds_bucket{ns=~\"$idxns\", idx=~\"$idxname\", instance=~\"$client\", run=~\"$QueryRun\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}